
spring:
  application:
    name: ${APP_NAME}
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};DatabaseName=${DB_NAME};encrypt=false;trustServerCertificate=false;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2016Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'

  jackson:
    serialization:
      fail-on-empty-beans: 'false'

server:
  port: ${APP_PORT}

springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui-custom.html